name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      env:
        DEPENDENCIES: cryptopp curl nlohmann-json opencv2
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        if [ "${{ runner.os }}" == "Windows" ]; then
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install ${{ env.DEPENDENCIES }}
        else
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install ${{ env.DEPENDENCIES }}
        fi

    - name: Configure CMake
      run: cmake -Bbuild

    - name: Build
      run: cmake --build build --config Release
     
    - name: Archive dist artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        if-no-files-found: error
        path: |
            build/Release/LicenseClient.dll
            build/Release/LicenseClient.so
