name: webhook

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    type: [ released ]
  workflow_call:

jobs:
  webhook:
    outputs:
      version: ${{ steps.version.outputs.version }}

    runs-on: windows-latest
    
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    steps:
      - name: Get latest tag
        id: version
        shell: python
        run: |
          import os
          import re
          import subprocess
          
          latest_tag = subprocess.check_output('git describe --abbrev=0 --tags', universal_newlines=True)
          version = re.search(pattern='v(?P<version>(\d+[.])+\d+)', string=latest_tag)['version']
          with open(os.getenv("GITHUB_OUTPUT", ""), "a") as fpa:
              fpa.write(f"version={version}")

      - name: Send event to PyLicenseClient
        env:
          VERSION: ${{ steps.version.outputs.version }}
        if: ${{ github.event_name == 'push' && github.ref_name == 'master'}}
        run: |
          curl -L `
          -X POST `
          -H "Accept: application/vnd.github+json" `
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" `
          -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/tov101/PyLicenseClient/dispatches `
          -d '{"event_type":"LicenseClient_v${{ env.VERSION }}","client_payload":{"tag": "v${{ env.VERSION }}"}}'